export default{
    'FETCH_DEFAULT':'FETCH_DEFAULT',
    'FETCH_MINGJU':'FETCH_MINGJU',
    'FETCH_GUJI':'FETCH_GUJI',
    'FETCH_ARTICLE':'FETCH_ARTICLE',
    'CHECK_LOGIN':'CHECK_LOGIN',
    'ADD_FAV':'ADD_FAV',
    'REMOVE_FAV':'REMOVE_FAV'
}