export default{
    'INIT':'INIT',
    
    //首页数据
    'MAIN_PAGE':'MAIN_PAGE',
    'APP_MENU':'APP_MENU',

    'APP_MENU_HISTROY':'APP_MENU_HISTROY',
    'APP_MENU_FAV':'APP_MENU_FAV',
    'APP_MENU_COLLECTION':'APP_MENU_COLLECTION',

    'APP_EXIT':'APP_EXIT',

    'APP_SETTING':'APP_SETTING',

    'APP_GOTO_DATE':'APP_GOTO_DATE',

    'CHECK_LOGIN':'CHECK_LOGIN',
    'ADD_FAV':'ADD_FAV',
    'REMOVE_FAV':'REMOVE_FAV',

    'GET_HISTORY':'GET_HISTORY',
    'APP_MINGJU':'APP_MINGJU',
    'APP_SHI':'APP_SHI',
    
    'GET_MINGJU_LIST':'GET_MINGJU_LIST',
    'GET_SHI_LIST':'GET_SHI_LIST',
    'GET_FAV':'GET_FAV',
    'GET_COLLECTION':'GET_COLLECTION',
    'UPDATE_COLLECTION':'UPDATE_COLLECTION',
    'REMOVE_COLLECTIOM':'REMOVE_COLLECTION'
}