export default [
    {
        name:'userList',
        type:'storage',
        defaultState:[
            {name:'default'}
        ]
    },
    {
        name:'currentUser',
        type:'storage',
        defaultState:{
            name:'default'
        }
    },
    {
        name:'fav',
        type:'storage'
    }
]